### PR TITLE
Fix ImportError with Selenium 4.40+: Replace AnyDevice import

### LINKED ISSUE #595: Incompatible with Selenium v.4.40.0
```
  File "/path/to/venv/Lib/site-packages/selene/core/_actions.py", line 30, in <module>
    from selenium.webdriver.common.action_chains import AnyDevice
ImportError: cannot import name 'AnyDevice' from 'selenium.webdriver.common.action_chains' (/path/to/venv/Lib/site-packages/selenium/webdriver/common/action_chains.py)
```

Broken by: https://github.com/SeleniumHQ/selenium/commit/88273fde1d08b79d0341049f29751b05fe109b7d#diff-2252da278d5aef6ec4ad66a1f179282ce0b1aea21d6fb07995e4122a0b198390R24-L33

Basically - a type alias was deleted, so now Selene needs to declare it by itself for its own usage.
Alternatively, which would be worse, you could pin selenium dependency to `<=4.39.0`.

### LINKED ISSUE #596: ImportError: cannot import name 'AnyDevice' from 'selenium.webdriver.common.action_chains' with Selenium 4.43.0
selene 2.0.0rc9 fails to import when paired with selenium >= 4.43.0. The error occurs at startup before any test execution.

  **Error:**

  selene/core/_actions.py:30: in <module>
      from selenium.webdriver.common.action_chains import AnyDevice
  E   ImportError: cannot import name 'AnyDevice' from 'selenium.webdriver.common.action_chains'

  **Environment:**
  - Python: 3.10
  - selene: 2.0.0rc9
  - selenium: 4.43.0 (works with 4.33.0)
  - OS: macOS (Darwin 23.3.0)

  **Steps to reproduce:**

  1. Install selene==2.0.0rc9 with selenium>=4.43.0
  2. Import selene: from selene import Element
  3. ImportError is raised immediately

  **Root cause:**

  selene/core/_actions.py line 30 imports AnyDevice from selenium.webdriver.common.action_chains. This symbol was available in Selenium 4.33.0 but appears to have been removed or relocated in Selenium 4.43.0.

  Import chain:
  selene.__init__
    → selene.core._browser
      → selene.core._actions
        → selenium.webdriver.common.action_chains.AnyDevice  ← missing

  **Workaround:**

  Pin selenium to a compatible version: selenium==4.33.0

### PR DESCRIPTION
**Pull request by VladPetrov-QAA**
- Replace direct import of AnyDevice from action_chains
- Define AnyDevice as Union type alias locally
- Fixes #596: ImportError with Selenium 4.43.0
- Fixes #595: Incompatible with Selenium v.4.40.0

The AnyDevice type was removed from selenium.webdriver.common.action_chains in Selenium 4.40+. This patch defines it locally as a type alias to maintain backward compatibility.

Based on Selene 2.0.0rc9 (commit: 4d7b027f)

Tested with:
- Selenium 4.43.0
- Python 3.12
- All existing functionality preserved

### CODE REVIEW

**Comment by aleksandr-kotlyar** [comment]
Thanks a lot for this PR and for the clean Selenium 4.40+ compatibility fix.

Really appreciate that you:

- pinpointed the exact root cause (AnyDevice removal from action_chains);
- provided a minimal, safe patch via a local type alias;
- included clear context and validation details (Selenium 4.43.0 / Python 3.12).

This is a valuable stability improvement for selene-2.0.0rc9+. Thank you for the contribution!
